In [3]:
import pandas as pd

In [4]:
train = pd.read_csv("train2016.csv")

In [5]:
train.head(5)

,USER_ID,YOB,Gender,Income,HouseholdStatus,EducationLevel,Party,Q124742,Q124122,Q123464,...,Q100010,Q99716,Q99581,Q99480,Q98869,Q98578,Q98059,Q98078,Q98197,Q96024
0,1,1938.0,Male,NaN,Married (w/kids),NaN,Democrat,No,NaN,No,...,Yes,No,No,NaN,No,NaN,Only-child,No,No,Yes
1,4,1970.0,Female,"over $150,000",Domestic Partners (w/kids),Bachelor's Degree,Democrat,NaN,Yes,No,...,NaN,NaN,NaN,No,No,No,Only-child,Yes,No,No
2,5,1997.0,Male,"$75,000 - $100,000",Single (no kids),High School Diploma,Republican,NaN,Yes,Yes,...,Yes,No,No,No,Yes,No,Yes,No,Yes,No
3,8,1983.0,Male,"$100,001 - $150,000",Married (w/kids),Bachelor's Degree,Democrat,No,Yes,No,...,No,No,No,Yes,Yes,No,Yes,No,No,Yes
4,9,1984.0,Female,"$50,000 - $74,999",Married (w/kids),High School Diploma,Republican,No,Yes,No,...,Yes,No,No,Yes,No,No,Yes,No,No,Yes

In [6]:
train

,USER_ID,YOB,Gender,Income,HouseholdStatus,EducationLevel,Party,Q124742,Q124122,Q123464,...,Q100010,Q99716,Q99581,Q99480,Q98869,Q98578,Q98059,Q98078,Q98197,Q96024
0,1,1938.0,Male,NaN,Married (w/kids),NaN,Democrat,No,NaN,No,...,Yes,No,No,NaN,No,NaN,Only-child,No,No,Yes
1,4,1970.0,Female,"over $150,000",Domestic Partners (w/kids),Bachelor's Degree,Democrat,NaN,Yes,No,...,NaN,NaN,NaN,No,No,No,Only-child,Yes,No,No
2,5,1997.0,Male,"$75,000 - $100,000",Single (no kids),High School Diploma,Republican,NaN,Yes,Yes,...,Yes,No,No,No,Yes,No,Yes,No,Yes,No
3,8,1983.0,Male,"$100,001 - $150,000",Married (w/kids),Bachelor's Degree,Democrat,No,Yes,No,...,No,No,No,Yes,Yes,No,Yes,No,No,Yes
4,9,1984.0,Female,"$50,000 - $74,999",Married (w/kids),High School Diploma,Republican,No,Yes,No,...,Yes,No,No,Yes,No,No,Yes,No,No,Yes
5,10,1997.0,Female,"over $150,000",Single (no kids),Current K-12,Democrat,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,11,1983.0,Male,"$25,001 - $50,000",Married (no kids),Current Undergraduate,Democrat,NaN,NaN,NaN,...,Yes,NaN,NaN,NaN,No,No,Yes,No,Yes,Yes
7,12,1996.0,Male,"$75,000 - $100,000",Single (no kids),Current K-12,Republican,Yes,Yes,No,...,Yes,No,No,Yes,Yes,No,Yes,No,Yes,Yes
8,13,NaN,Male,NaN,Single (no kids),Current K-12,Republican,No,NaN,Yes,...,Yes,No,No,Yes,Yes,No,Yes,NaN,NaN,Yes
9,15,1981.0,Female,"$50,000 - $74,999",Married (w/kids),NaN,Republican,No,No,No,...,Yes,No,No,Yes,Yes,No,Yes,Yes,Yes,No
10,16,1971.0,Male,"over $150,000",Married (no kids),Bachelor's Degree,Republican,NaN,NaN,NaN,...,Yes,No,Yes,Yes,Yes,NaN,NaN,NaN,NaN,Yes
11,17,1977.0,Female,"$100,001 - $150,000",Domestic Partners (no kids),Bachelor's Degree,Republican,Yes,No,No,...,Yes,No,No,Yes,Yes,No,Only-child,Yes,No,Yes
12,18,1971.0,Male,"$50,000 - $74,999",Married (w/kids),High School Diploma,Democrat,No,Yes,No,...,No,No,No,Yes,Yes,No,Yes,Yes,Yes,Yes
13,19,1996.0,Male,"$75,000 - $100,000",Single (no kids),Current K-12,Republican,Yes,No,No,...,No,No,No,Yes,No,Yes,Yes,No,No,Yes
14,20,1970.0,Male,"$75,000 - $100,000",Married (w/kids),Bachelor's Degree,Republican,NaN,NaN,NaN,...,Yes,No,No,Yes,Yes,No,Yes,No,No,Yes
15,21,1979.0,Male,"over $150,000",Married (w/kids),Bachelor's Degree,Republican,No,No,No,...,Yes,No,No,Yes,Yes,No,Yes,No,Yes,Yes
16,22,1997.0,Female,"$75,000 - $100,000",Single (no kids),NaN,Democrat,NaN,NaN,NaN,...,NaN,No,NaN,NaN,NaN,No,Yes,NaN,No,Yes
17,23,1976.0,Male,"$50,000 - $74,999",Married (no kids),Bachelor's Degree,Democrat,NaN,No,No,...,Yes,No,No,Yes,No,No,Yes,Yes,No,Yes
18,24,1982.0,Female,"$25,001 - $50,000",Single (no kids),Master's Degree,Democrat,Yes,No,No,...,Yes,Yes,No,Yes,Yes,No,Yes,Yes,Yes,Yes
19,25,1973.0,Male,"$75,000 - $100,000",Married (w/kids),Associate's Degree,Democrat,No,Yes,No,...,Yes,No,No,Yes,Yes,No,Yes,No,No,No
20,26,1993.0,Female,"$50,000 - $74,999",Domestic Partners (no kids),High School Diploma,Republican,NaN,Yes,No,...,No,No,No,No,Yes,No,Yes,Yes,No,Yes
21,27,1970.0,Male,"over $150,000",Domestic Partners (w/kids),Master's Degree,Democrat,Yes,Yes,No,...,Yes,No,No,No,Yes,Yes,Yes,No,Yes,Yes
22,30,1995.0,Male,"$75,000 - $100,000",Single (no kids),Current K-12,Democrat,NaN,Yes,No,...,No,No,No,Yes,Yes,Yes,Yes,NaN,NaN,Yes
23,31,1996.0,Male,NaN,NaN,Current K-12,Democrat,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,32,1993.0,Male,"$75,000 - $100,000",Single (no kids),Current Undergraduate,Republican,No,Yes,No,...,Yes,No,No,Yes,No,No,Yes,Yes,No,No
25,33,1951.0,Female,"$50,000 - $74,999",Married (w/kids),Master's Degree,Democrat,NaN,No,No,...,Yes,No,No,Yes,No,No,Yes,No,No,No
26,34,1950.0,Female,NaN,Married (no kids),Associate's Degree,Democrat,NaN,Yes,No,...,Yes,No,No,Yes,Yes,No,Only-child,No,No,No
27,35,1996.0,Male,"over $150,000",Single (no kids),Current K-12,Democrat,Yes,No,No,...,Yes,No,No,No,No,Yes,Yes,No,No,Yes
28,36,1977.0,Female,"$25,001 - $50,000",Single (no kids),Bachelor's Degree,Democrat,No,No,No,...,Yes,Yes,No,No,Yes,No,Yes,Yes,NaN,Yes
29,38,1979.0,Female,"$75,000 - $100,000",Single (no kids),High School Diploma,Democrat,Yes,No,No,...,Yes,No,No,Yes,Yes,No,Yes,No,No,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5538,6926,1965.0,Female,"$25,001 - $50,000",Single (w/kids),High School Diploma,Republican,NaN,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5539,6927,1994.0,Male,"$100,001 - $150,000",Single (no kids),Current Undergraduate,Democrat,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5540,6929,1992.0,Female,NaN,Single (no kids),Current Undergraduate,Republican,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5541,6931,NaN,Male,"over $150,000",Single (no kids),Current K-12,Democrat,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5542,6932,1983.0,Female,"under $25,000",Single (no kids),Master's Degree,Republican,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5543,6933,1994.0,Female,"$25,001 - $50,000",Single (no kids),Current Undergraduate,Democrat,NaN,NaN,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5544,6934,NaN,Female,"$75,000 - $100,000",Married (w/kids),NaN,Republican,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5545,6935,1997.0,Female,NaN,Single (no kids),Current K-12,Republican,NaN,NaN,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5546,6936,NaN,Female,NaN,Single (no kids),Current K-12,Republican,NaN,Yes,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5547,6937,1976.0,Female,"$75,000 - $100,000",Married (w/kids),Bachelor's Degree,Democrat,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5548,6938,1987.0,Female,"$75,000 - $100,000",Married (w/kids),Bachelor's Degree,Republican,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5549,6939,1999.0,Female,NaN,Single (no kids),Current K-12,Democrat,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5550,6940,1994.0,Male,"$25,001 - $50,000",Domestic Partners (no kids),High School Diploma,Republican,No,Yes,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5551,6942,1998.0,Female,"over $150,000",Single (no kids),Current K-12,Republican,Yes,Yes,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5552,6943,NaN,Female,NaN,NaN,Current Undergraduate,Democrat,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5553,6944,1994.0,Male,"under $25,000",Single (no kids),Current Undergraduate,Democrat,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5554,6945,NaN,Male,"$50,000 - $74,999",Single (no kids),Current K-12,Democrat,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5555,6948,1997.0,Female,NaN,Single (no kids),Current K-12,Republican,Yes,Yes,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5556,6949,NaN,Male,NaN,NaN,NaN,Republican,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5557,6950,1989.0,Male,"$25,001 - $50,000",Single (w/kids),Bachelor's Degree,Republican,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5558,6951,1988.0,Female,"$25,001 - $50,000",Single (no kids),Current Undergraduate,Republican,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5559,6952,1945.0,Male,"$25,001 - $50,000",Married (w/kids),High School Diploma,Democrat,NaN,Yes,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5560,6953,1970.0,Female,NaN,Married (w/kids),Bachelor's Degree,Democrat,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5561,6954,NaN,Male,"$50,000 - $74,999",Single (no kids),Bachelor's Degree,Democrat,No,Yes,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5562,6955,1966.0,Male,"over $150,000",Married (w/kids),Bachelor's Degree,Democrat,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5563,6956,NaN,Male,NaN,NaN,Master's Degree,Democrat,NaN,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5564,6957,2000.0,Female,NaN,NaN,Current K-12,Republican,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5565,6958,1969.0,Male,"over $150,000",NaN,Bachelor's Degree,Democrat,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5566,6959,1986.0,Male,"$25,001 - $50,000",Married (w/kids),High School Diploma,Republican,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5567,6960,1999.0,Male,"under $25,000",Single (no kids),Current K-12,Republican,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
test = pd.read_csv("test2016.csv")

In [8]:
test

,USER_ID,YOB,Gender,Income,HouseholdStatus,EducationLevel,Q124742,Q124122,Q123464,Q123621,...,Q100010,Q99716,Q99581,Q99480,Q98869,Q98578,Q98059,Q98078,Q98197,Q96024
0,2,1985.0,Female,"$25,001 - $50,000",Single (no kids),Master's Degree,NaN,Yes,No,Yes,...,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
1,3,1983.0,Male,"$50,000 - $74,999",Married (w/kids),Current Undergraduate,NaN,NaN,No,NaN,...,NaN,NaN,NaN,NaN,Yes,NaN,Yes,Yes,No,Yes
2,6,1995.0,Male,"$75,000 - $100,000",Single (no kids),Current K-12,NaN,NaN,NaN,NaN,...,No,No,No,Yes,Yes,No,Yes,No,Yes,Yes
3,7,1980.0,Female,"$50,000 - $74,999",Single (no kids),Master's Degree,Yes,Yes,No,Yes,...,Yes,No,No,No,Yes,No,Yes,No,No,Yes
4,14,1980.0,Female,NaN,Married (no kids),Current Undergraduate,NaN,Yes,No,Yes,...,Yes,No,No,Yes,No,No,Yes,No,No,No
5,28,1973.0,Male,"over $150,000",Married (no kids),Master's Degree,No,Yes,No,Yes,...,Yes,No,No,Yes,No,No,Yes,No,No,Yes
6,29,1968.0,Female,"$50,000 - $74,999",Single (no kids),Bachelor's Degree,NaN,NaN,NaN,NaN,...,Yes,NaN,No,Yes,Yes,NaN,Yes,No,Yes,NaN
7,37,1961.0,Male,"over $150,000",Domestic Partners (no kids),High School Diploma,NaN,Yes,No,Yes,...,Yes,No,NaN,NaN,NaN,No,Yes,NaN,NaN,NaN
8,44,1989.0,Female,"under $25,000",Single (no kids),High School Diploma,NaN,Yes,No,Yes,...,No,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No
9,56,1975.0,Male,"$75,000 - $100,000",Married (w/kids),Bachelor's Degree,No,NaN,No,Yes,...,Yes,No,Yes,No,Yes,No,Yes,Yes,No,No
10,62,1958.0,Female,"$50,000 - $74,999",Domestic Partners (no kids),Bachelor's Degree,No,No,NaN,NaN,...,Yes,No,No,Yes,NaN,NaN,NaN,NaN,NaN,No
11,68,1960.0,Female,"$75,000 - $100,000",Married (w/kids),Master's Degree,No,Yes,No,No,...,Yes,No,NaN,Yes,No,No,Yes,Yes,Yes,No
12,72,1985.0,Male,"$50,000 - $74,999",Single (no kids),High School Diploma,NaN,NaN,No,Yes,...,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,74,1978.0,Male,"$50,000 - $74,999",Single (w/kids),Current Undergraduate,NaN,NaN,No,NaN,...,Yes,No,No,Yes,Yes,NaN,Yes,Yes,Yes,NaN
14,80,1998.0,Female,"$75,000 - $100,000",Single (no kids),Current K-12,Yes,Yes,No,No,...,Yes,No,No,Yes,Yes,No,Yes,No,No,Yes
15,81,1966.0,Male,"over $150,000",Married (w/kids),Master's Degree,No,Yes,No,Yes,...,Yes,No,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes
16,87,1990.0,Male,"$25,001 - $50,000",Single (no kids),Bachelor's Degree,No,Yes,No,No,...,Yes,No,No,No,Yes,Yes,Only-child,Yes,No,Yes
17,92,1984.0,Male,"$100,001 - $150,000",Single (no kids),Bachelor's Degree,No,No,No,Yes,...,Yes,Yes,No,No,No,Yes,Yes,No,No,Yes
18,96,1983.0,Male,"$75,000 - $100,000",Married (w/kids),Master's Degree,NaN,Yes,No,Yes,...,No,No,No,No,Yes,No,Only-child,No,No,Yes
19,100,1979.0,Male,"$100,001 - $150,000",Married (w/kids),Bachelor's Degree,NaN,Yes,No,Yes,...,Yes,No,No,Yes,Yes,Yes,Yes,No,No,Yes
20,104,1985.0,Male,"$25,001 - $50,000",Married (no kids),Bachelor's Degree,No,No,No,Yes,...,Yes,No,No,No,No,No,Only-child,No,No,No
21,105,1993.0,Female,"over $150,000",Married (w/kids),Current Undergraduate,NaN,No,No,No,...,NaN,No,No,Yes,Yes,No,Yes,Yes,Yes,NaN
22,108,1976.0,Male,"under $25,000",Single (no kids),High School Diploma,NaN,NaN,No,Yes,...,NaN,NaN,NaN,NaN,NaN,No,Yes,No,No,NaN
23,124,1981.0,Female,"under $25,000",Single (no kids),Bachelor's Degree,No,Yes,No,Yes,...,Yes,Yes,No,Yes,No,NaN,NaN,NaN,NaN,No
24,125,1975.0,Female,"$50,000 - $74,999",Single (no kids),NaN,NaN,No,NaN,Yes,...,Yes,No,No,Yes,Yes,NaN,Yes,NaN,NaN,Yes
25,127,1969.0,Male,"over $150,000",Single (w/kids),Doctoral Degree,Yes,Yes,No,Yes,...,Yes,Yes,No,No,Yes,Yes,Yes,Yes,No,Yes
26,128,1994.0,Female,NaN,Single (no kids),Current Undergraduate,No,No,NaN,No,...,Yes,No,No,Yes,Yes,No,Yes,No,Yes,NaN
27,129,1961.0,Male,NaN,Married (w/kids),NaN,No,No,No,Yes,...,NaN,No,No,Yes,NaN,NaN,NaN,NaN,NaN,Yes
28,130,1988.0,Female,"under $25,000",Single (no kids),Bachelor's Degree,NaN,No,No,No,...,NaN,NaN,No,Yes,NaN,NaN,Yes,Yes,Yes,No
29,139,1990.0,Male,"$25,001 - $50,000",Married (no kids),Bachelor's Degree,Yes,Yes,No,Yes,...,Yes,No,No,Yes,Yes,No,Yes,No,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1362,6830,1985.0,Female,"$50,000 - $74,999",Domestic Partners (w/kids),Bachelor's Degree,No,Yes,No,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1363,6837,1987.0,Male,"$75,000 - $100,000",Married (no kids),Master's Degree,No,Yes,No,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1364,6843,1989.0,Female,"$25,001 - $50,000",Married (w/kids),Bachelor's Degree,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1365,6844,1997.0,Male,NaN,NaN,Current K-12,Yes,Yes,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1366,6845,1995.0,Male,"$100,001 - $150,000",Single (no kids),Current Undergraduate,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1367,6848,1987.0,Male,NaN,Single (no kids),Associate's Degree,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1368,6852,NaN,Male,NaN,NaN,Current K-12,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1369,6859,1998.0,Male,"under $25,000",Single (no kids),Current K-12,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1370,6860,1994.0,Female,NaN,Single (no kids),Current Undergraduate,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1371,6864,1995.0,Female,"$25,001 - $50,000",NaN,Current Undergraduate,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1372,6865,1976.0,Male,"$50,000 - $74,999",Married (w/kids),High School Diploma,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1373,6867,NaN,Female,"under $25,000",Single (no kids),Current K-12,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1374,6870,1997.0,Male,"under $25,000",Single (no kids),Current K-12,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1375,6871,1990.0,Male,"$75,000 - $100,000",Single (no kids),Master's Degree,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1376,6876,1981.0,Female,"$50,000 - $74,999",Single (w/kids),Master's Degree,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1377,6879,1994.0,Female,NaN,Single (no kids),Current Undergraduate,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1378,6887,NaN,Female,NaN,Single (no kids),Current K-12,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1379,6892,1973.0,Male,"$75,000 - $100,000",Single (no kids),Bachelor's Degree,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1380,6895,1990.0,Female,"under $25,000",Married (no kids),Current Undergraduate,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1381,6898,NaN,Male,"over $150,000",Married (w/kids),Master's Degree,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1382,6904,1991.0,Female,"under $25,000",Single (no kids),Current Undergraduate,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1383,6914,1992.0,Male,NaN,Single (no kids),Associate's Degree,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1384,6919,1998.0,Female,"under $25,000",Single (no kids),Current K-12,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1385,6921,1995.0,Female,NaN,Single (no kids),Current K-12,NaN,Yes,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1386,6922,1988.0,Male,"$50,000 - $74,999",Single (no kids),Master's Degree,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1387,6928,1977.0,Female,"$50,000 - $74,999",Domestic Partners (no kids),Master's Degree,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1388,6930,1998.0,Female,"$100,001 - $150,000",Single (no kids),Current K-12,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1389,6941,1989.0,Male,"$25,001 - $50,000",Married (no kids),Bachelor's Degree,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1390,6946,1996.0,Male,NaN,NaN,Current K-12,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1391,6947,NaN,Female,NaN,NaN,NaN,Yes,Yes,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
 import openpyxl